tensortrade-org/tensortrade

- tensortrade/actions/continuous/simple_continuous_strategy.py
- tensortrade/actions/discrete/simple_discrete_strategy.py
- tensortrade/agents/trading_agent.py
- tensortrade/environments/trading_environment.py
- tensortrade/exchanges/asset_exchange.py
- tensortrade/performance/trading_performance.py
- tensortrade/rewards/simple/incremental_profit_strategy.py
Hi Adam, I added some docs to get to know the code base a bit!
> Adding docstrings

- Dockerfile
- Makefile
- README.md
- docs/source/overview/getting_started.md
- requirements.txt
- setup.py
- tensortrade/features/indicators/talib_indicator.py
I've finished my work on the Docker infrastructure. I had to make some changes to the versions of tensorforce to get things running.
> Built necessary Docker infrastructure to run python notebooks, build documentation, and run test suite

- Dockerfile
- requirements.txt
Fix and optimize the dockerfile and requirements.txt to make the examples runnable
> Fix the dockerfile to run the examples

- Dockerfile
- Makefile
- requirements.txt
I worked on fixing the run-notebook command. There were issues while building the dockerfile supplied. I made modifications to get it working on Ubuntu version: 18.04 an up.
> fixed make run-notebook

- tensortrade/strategies/__init__.py
This is a sample solution for issue #75
> Conditionally load strategies depending on installed modules

- examples/requirements.txt
- examples/tf2_playground.ipynb
Fixed the loop breaking in the tf2 example
Added requirements for ta-lib and scikit-learn to examples
> Couple of fixes for examples and Docker

- tests/tensortrade/test_component_registration.py
Add one missing test skip and fix one duplicated assert.
> Minor unit test fixes

- .travis.yml
- Dockerfile
- tensortrade/features/indicators/ta_indicator.py
- tests/tensortrade/features/indicators/test_ta_indicator.py
Merging @daHIFI's work into master
> Ta indicator @daHIFI

- docs/source/components/environments/TradingEnvironment.md
- docs/source/components/exchanges/live/CCXTExchange.md
- docs/source/components/exchanges/live/InteractiveBrokersExchange.md
- docs/source/components/features/FeaturePipeline.md
- docs/source/components/features/indicators/TAlibIndicator.md
- docs/source/components/features/scalers/MinMaxNormalizer.md
- docs/source/components/features/scalers/StandardNormalizer.md
- docs/source/components/features/stationarity/FractionalDifference.md
- docs/source/components/rewards/RiskAdjustedReturnStrategy.md
- docs/source/components/rewards/SimpleProfitStrategy.md
- docs/source/components/strategies/StableBaselinesTradingStrategy.md
- docs/source/components/strategies/TensorforceTradingStrategy.md
I just realized I had cleaning changes inside of another folder.
> Replace with use cases

- tensortrade/actions/dynamic_orders.py
- tensortrade/actions/managed_risk_orders.py
- tensortrade/orders/create.py
- tensortrade/orders/order.py
- tensortrade/orders/order_spec.py
- tensortrade/orders/trade.py
The selection is repeated all over.
The semantic wheather base or quote is relevant
comes from TradeSide. So implementing it there.
> Place order/trade instrument semantic in TradeSide

- .travis.yml
https://mypy.readthedocs.io
Travis CI is not turned on at https://travis-ci.com/tensortrade-org/tensortrade
> Travis CI: Test Python type hints using mypy

- tensortrade/rewards/risk_adjusted_returns.py
Change the get_reward() method in risk_adjusted_returns.py to get pct_change() instead of diff()
> get reward to get pct_change not the diff

- tensortrade/actions/dynamic_orders.py
fix getting proper quote for pair instead of instrument + return early if action is not sell/hold
> fix getting proper quote for pair instead of instrument

- tensortrade/rewards/risk_adjusted_returns.py
- tests/tensortrade/unit/rewards/test_risk_adjusted_returns.py
> Match net worth calculation in test to tested method in TestRiskAdjustedReturns

- tensortrade/environments/render/base_renderer.py
An error was raised when I ran the agent training at the `renderers_and_plotly_chart.ipynb` code. It fixed it.
> Small fix: typing and string formatting

- tensortrade/env/default/renderers.py
This both fixes an error with MatplotlibTradingChart, and honors the "display" request for PlotlyTradingChart
> Fix MatplotlibTradingChart and PlotlyTradingChart renderers

- examples/train_and_evaluate.ipynb
> Update example since coinbase is not available anymore

- tensortrade/agents/a2c_agent.py
- tensortrade/agents/dqn_agent.py
This is in regards to issue #197
> Add time stamp to saved model file name and use shorter id

- tensortrade/oms/wallets/portfolio.py
> Fix percent loss calculation

- tensortrade/env/default/actions.py
This might fix issues of having an order commission under precision.
Also, I don't know why "value" was calculated before, since size is already the order size expressed in base asset, and it's not used anywhere else.
@rhamnett can you doublecheck this?
LGTM anyway
> Fix minimum order pct and abs

- tensortrade/env/default/observers.py
This is the edit done in issue #284 implemented in a PR
> Fix multiplication for Stream object #292

- tensortrade/data/cdd.py
Hi!
I want to use Binance data. In CDD data some of the timestamps use milliseconds and others use seconds so I normalized them.
gr,
Tom
> Use unix timestamp as date source

- tensortrade/core/component.py
"its" is the possessive form. "it's" is a contraction of "it" and "is".
> Nit: grammar fix

- tensortrade/agents/dqn_agent.py
> More features, normalization, parameter fixes.

- .travis.yml
- Pipfile.lock
- requirements.txt
- setup.py
- tensortrade/env/default/actions.py
- tensortrade/env/default/observers.py
- tensortrade/env/generic/components/action_scheme.py
- tensortrade/env/generic/components/observer.py
- tensortrade/env/generic/environment.py
Thanks to @MaxLoedige for the fix to implement gymnasium style envs
> Bump to gymnasium and update dependencies to Python 3.11.9
