tensortrade/exchanges/live/ccxt_exchange.py, tensortrade/rewards/risk_adjusted_return_strategy.py
Identity is not the same thing as equality in Python.
[Porting to Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html#porting-to-python-3-8)
> The compiler now produces a SyntaxWarning when identity checks (is and is not) are used with certain types of literals (e.g. strings, numbers). These can often work by accident in CPython, but are not guaranteed by the language spec. The warning advises users to use equality tests (== and !=) instead. (Contributed by Serhiy Storchaka in bpo-34850.)
[flake8](http://flake8.pycqa.org) testing of https://github.com/notadamking/tensortrade on Python 3.8.0
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./tensortrade/rewards/risk_adjusted_return_strategy.py:40:12: F632 use ==/!= to compare str, bytes, and int literals …
```
=> Use ==/!= to compare str, bytes, and int literals

tensortrade/exchanges/simulated/simulated_exchange.py
Any value for `window_size` larger than `1` currently causes the `SimulatedExchange` implementation to return empty data frames for the first few steps (empty data frames, not data frames filled with NaNs, but data frames without any columns). But, any `FeatureTransformer` expects a data frame to exactly fit the observation space, which thus causes any training to crash.
The issue itself is caused by [Line 128](https://github.com/notadamking/tensortrade/blob/master/tensortrade/exchanges/simulated/simulated_exchange.py#L128), which generates the observations:
```obs = self._data_frame.iloc[step - self._window_size + 1:step + 1]```
With any value for `window_size` greater than 1, this line will query negative index at the first step. For example something like [-5:1] for a window of 6 at …
=> Fix `window_size` larger then 1 in `SimulatedExchange`

tensortrade/strategies/stable_baselines_strategy.py
the current statement eposide_callback(self._environment._exchange.performance) on line number 112 isnt working
Changed it to episode_callback(performance) since they're technically same things
also, episode_callback() returning true (as per the documentation) breaks the loop (which should be reverse) .. added a not in the if condition.
=> fixed broken episode_callback in stable_baselines_strategy.py

tensortrade/features/scalers/percent_change_normalizer.py
the default value should be feature_midpoint; zeros are likely to be very confusing for anything working with the data
=> no change values are designated by feature_midpoint, not 0. oops.

tensortrade/exchanges/simulated/fbm_exchange.py
1. a simple addition to make sure that the data_frame.shape(0) == times_to_generate Independent of time frame
2. Reduce unnecessary computation
=> make sure to get the expected data frame length

tensortrade/agents/a2c_agent.py, tensortrade/agents/dqn_agent.py
With commit https://github.com/tensortrade-org/tensortrade/commit/22b47fb67b95b08039fa335bed6053d97c7052f9, `train` now returns the mean reward but  the A2C and DQN agents return the reward prematurely. Only one episode runs. This change returns the mean reward after all the steps and episodes are completed.
=> Fix reward being returned early after the first episode

tensortrade/agents/a2c_agent.py
In a2c_agent.py the returns tensor must be reshaped in order to calculate the avantages correctly. That way the error described in Issue #187 is resolved.
=> Reshape returns Tensor in a2c_agent.py

tensortrade/agents/a2c_agent.py, tensortrade/agents/dqn_agent.py
The outer while loop in the agent's train method was checking that the
current episode is not greater than the requested number of episodes but
the episode counter was not being incremented. This caused an infinite
loop if you did not specify number of steps.
=> Fix episode counter not being incremented in dqn and a2c agents

tensortrade/agents/dqn_agent.py
At this moment exploration ratio gets reset on every episode during training. This makes agent choose random action  way too often.
---
This is how exploration ratio looks during training on current master:
---
This is how it should look (from Q Learning articles):
---
This is how it looks like with this bugfix:
=> Fix for exploration/exploitation ratio

tensortrade/env/default/actions.py
This stops multiple remedial orders flowing through when net_worth fluctuates.
=> Add min_order_pct to Simple Orders

tensortrade/env/default/renderers.py
A simple bug that converts the underlying OrderedDict back into a pandas dataframe for rendering. Perhaps not the most performant fix, but the simplest, which I believe will do for now.
=> fixed bug in renderer.py

tensortrade/stochastic/processes/fbm.py, tensortrade/stochastic/processes/gbm.py, tensortrade/stochastic/processes/merton.py, tensortrade/stochastic/processes/ornstein_uhlenbeck.py, tensortrade/stochastic/utils/helpers.py
Fixed errors caused by stochastic's recent file rearrangement. Now GaussianNoise and FractionalBrownianMotion refer to classes in the correct place.
=> Fixed references to GaussianNoise and FractionalBrownianMotion broken by stochastic's recent file rearrangement

tensortrade/data/cdd.py
The CSV headers from https://www.cryptodatadownload.com/cdd/ changed, so the current code was not working. Updated symbol field name and datetime format to make it work again.
=> Updating `CryptoDataDownload()` to sync with current CSV

tensortrade/feed/api/float/window/ewm.py, tensortrade/feed/api/float/window/expanding.py, tensortrade/feed/api/float/window/rolling.py
Added reset function overrides to RollingNode and Rolling classes
Observer feed reset missed clearing members of rolling classes causing stale data from feed initialization to remain resulting in incorrect values after environment reset.
=> Reset fix for rolling calculations

tensortrade/env/default/actions.py
Without this, the agent tries to place an order even with 0 USD balance, using 100% of said balance. It tries to place an order of 0 USD which raises an error.
=> BSH: check for balance prior to ordering

tensortrade/env/default/stoppers.py
Fixes comparison operator, meaning that max_allowed_loss set to 0.01 will allow balance to drop to 99% of the original value (hence losing 1%) before stopping the run.
=> Fix max_allowed_loss operator and description

tensortrade/env/default/actions.py, tensortrade/oms/exchanges/exchange.py, tensortrade/oms/services/execution/simulated.py
Added a flag to ExchangeOptions that defaults to the current behavior. If set to true it will match the commission with the minimum value that the precision allows, proceeding with the trade.
=> Log warnings when precision is less than commission

docs/source/components/observer.md, tensortrade/env/default/observers.py
In IntradayObserver each episode is a single trading day. Takes additional parameters of stop_time (datetime.time) and randomize (bool). stop_time is the time (from DataFeed timestamp) that marks the end of the episode. randomize determines if the episode (trading day) should be selected randomly or in order. IntradayObserver requires the feed to include a Stream of Timestamps named 'timestamp'.
=> Add IntradayObserver

tensortrade/env/default/actions.py
This allows to set a fixed minimum order amount, useful in the case an exchange has a minimum order limit (not optimal because it should be an exchange property, but it's a workaround), and in the case you don't want to have the bot "micromanage" positions, but focus on bigger than a threshold value orders.
=> Add min_order_abs to SimpleOrders

tensortrade/feed/core/base.py
The usage of `super().__new__(cls, *args, **kwargs)` leads to an exception of the kind:
```python
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```
The easy fix is to avoid passing args and kwargs to the superclass' `__new__` method.
However i don't know this codebase. I was just trying to run my very first example using this library and got stuck at this error. The example manages to run with my change.
BUT i see that the `Stream` class inherits from multiple classes (`Generic[T], Named, Observable`), and MAYBE the problem raises from method resolution order?
Edit: i should mention I'm using Python 3.9.
=> Fix Stream __new__ method causing TypeError in the documentation's code

tensortrade/feed/core/base.py
Only listeners were being reset. The Stream class had members that needed to be reset as well.
=> Base stream reset fix

tensortrade/oms/instruments/quantity.py, tensortrade/oms/orders/broker.py, tensortrade/oms/orders/create.py, tensortrade/oms/wallets/wallet.py
Removing the executed order from the list in the for loop breaks the loop.
```
a = ["a","b","c","d","e"]
for i,l in enumerate(a):
print(i,l)
if l=="b":
a.remove(l)
print(a)
```
```
0 a
1 b
2 d
3 e
['a', 'c', 'd', 'e']
```
=> Small modifications to allow multiple orders being executed in one environment step

Makefile
Hi!
I had started tensortrade a few days ago and made some changes in some files. I exited the docker process and restarted it a few days later to find that my changes had not persisted.
This change mounts the examples directory as a volume. As you make changes in Jupyter, they are saved on disk.
=> feat(docker): mount examples as volume

examples/renderers_and_plotly_chart.ipynb
Fix small typo in the documentation. I had to spend some time to figure out the issue, so hope this fix will save time to others.
=> fix: fix typo in renderers documentation example

tensortrade/env/default/rewards.py
This also solves a very rare bug that could happen with very small net worth arrays in regards to the reward window size
=> rewards calculation speedup ft. Ingolf Sommer
